Controllers films users
CoulthardDC/java-filmorate pull request #1
Opened 2022-11-26 20:34 UTC by CoulthardDC

Реализован основной функционал filmorate.  Добавлены тесты валидации. Добавлена валидация через аннотации.

2022-11-26 20:45 UTC, CoulthardDC commented
Прошу прощения за столь долгую сдачу ТЗ. По работе был очень загружен

2022-11-27 17:45 UTC, ErkinKasymaliev requested changes
Привет, отличная работа!
Свои аннотации - это очень круто!
только я не понял зачем вы в моделях поставили final. Надо добавить модификаторы доступа также.

2022-11-27 17:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FilmReleaseDateConstraint.java
> +public @interface FilmReleaseDateConstraint {
красава!

2022-11-27 17:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    final String name;
а зачем final к полям добавили? он не нужен, надо добавить модификаторы доступа

2022-11-27 17:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    final String email;
а зачем final к полям добавили? он не нужен, надо добавить модификаторы доступа

2022-11-27 17:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequestMapping(value = "/films")
правильно, что сразу path указали

2022-11-27 17:50 UTC, CoulthardDC commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    final String email;
По поводу модификаторов доступа: я ведь их добавил через аннотацию над классами film и user:
```java
@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Film {
    Integer id;
    @NotBlank
    final String name;
    @Size(max = 200)
    final String description;
    @FilmReleaseDateConstraint
    final LocalDate releaseDate;
    @Positive
    final Long duration;
}
```

2022-11-27 17:50 UTC, CoulthardDC commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    final String email;
А final сейчас исправлю.

2022-11-27 18:01 UTC, CoulthardDC commented
Убрал `final`, но из-за этого пришлось добавить конструктора к классу `Film`. По поводу модификаторов доступа: над классами-моделями я поставил аннотацию с модификатором доступа для полей по умолчанию - `private`

2022-11-27 18:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    final String email;
ооо, круто, даже не обратил внимание на эту аннотацию

2022-11-27 18:30 UTC, ErkinKasymaliev approved these changes
все круто, работа принята

2022-11-29 18:40 UTC, merged