feate: реализовать лайки и друзей
CoulthardDC/java-filmorate pull request #2
Opened 2022-12-02 17:20 UTC by CoulthardDC

Добрый вечер. Если будет возможность, прошу написать маленький комментарий по поводу того, что именно в сервисе проводятся проверки различных значений (например верный ли id был передан из контроллера, или верный ли count. Или стоило это проверять в самом контроллере). Также в сервисах я выкидывал исключения, которые потом отлавливал в контроллерах и формировал ответы на ошибочные запросы. Заранее спасибо

2022-12-03 20:30 UTC, CoulthardDC commented
Добрый вечер. Чуть зарефакторил код.

2022-12-04 08:27 UTC, ErkinKasymaliev commented
> Добрый вечер. Если будет возможность, прошу написать маленький комментарий по поводу того, что именно в сервисе проводятся проверки различных значений (например верный ли id был передан из контроллера, или верный ли count. Или стоило это проверять в самом контроллере). Также в сервисах я выкидывал исключения, которые потом отлавливал в контроллерах и формировал ответы на ошибочные запросы. Заранее спасибо

валидация может быть как и в сервисах, так и в самих контроллерах. У вас же все сделано корректно. В контроллере вы вальсируете входные параметры из запроса, в сервисах проверяете на наличие данных.

2022-12-04 08:28 UTC, ErkinKasymaliev requested changes
Здравствуйте, работа очень хорошая!
Но давайте поправим 1 коммент и будет конфетка

2022-12-04 08:28 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.findById(id).orElseThrow(() -> new FilmNotFoundException(id));
отлично!

2022-12-04 08:28 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.findById(userId).orElseThrow(
это конструкцию у вас часто дублируется. Давайте уберем в private метод, например, checkUsersId(List<Integer> usersIds)

2022-12-04 08:59 UTC, CoulthardDC commented
Вынес в отдельный метод конструкцию с `orElseThrow(() -> new ...)`. Не очень понял про метод `checkUsersId(List usersIds)` с листом в параметрах, т.к. подобный метод будет возвращать тоже лист (юзеров или фильмов) и его придется распаковывать по двум пользователям, т.е. писать что то в духе:
```java
user = resultOfCheck.get(0)
friend = resultOfCheck.get(1)
```

2022-12-04 11:24 UTC, ErkinKasymaliev commented
то что вы сделали пойдет

2022-12-04 11:24 UTC, ErkinKasymaliev approved these changes
отлично, работа принята

2022-12-05 16:00 UTC, merged