feat: добавить БД
CoulthardDC/java-filmorate pull request #4
Opened 2022-12-27 19:41 UTC by CoulthardDC

2022-12-27 19:49 UTC, CoulthardDC commented
Добрый вечер и с наступающим Новым  Годом!) По коду есть много негладких моментов, так что в будущем планирую сделать большой рефакторинг. Но так как скоро жесткий дедлайн, высылаю сейчас данный вариант. Он вполне рабочий, но буду менять)

2022-12-28 14:12 UTC, ErkinKasymaliev requested changes
Привет, оставил комменты.

2022-12-28 14:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        films.forEach(this::setGenresAndLikes);
вот так не надо. Вы тут делаете столько запросов сколько у вас фильмов. Если их у вас 1000, то 1000 запросов - а это не совсем круто;
Вам надо исправить  setGenresAndLikes(), в входном параметре будет не Film film, List<Films> films.
а в запросе не where film_id = ?, where film_id in (...). Как то так) а еще лайки есть)

2022-12-28 14:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        }, film.getId());
а где вы сеттите лайки?

2022-12-28 14:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                String sqlRequest = "DELETE from film_genres WHERE film_id = ?";
давайте уберем в отдельный метод сохранени жанров

2022-12-28 14:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            jdbcTemplate.batchUpdate(sqlRequest, new BatchPreparedStatementSetter() {
неплохо

2022-12-28 14:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +                .map(this::setFriends)
смотрите аналогичный коммент в FilmDbStorage в методе findAll()

2022-12-30 08:53 UTC, ErkinKasymaliev approved these changes
привет, отлично! работа принята

2023-01-12 19:03 UTC, merged